9taetae9/algorithm-study

Programmers/taehyoun/문자열 나누기.java
처음 제출 코드랑 개선해본 코드 둘다 올려봤습니다!
처음 풀때는 toChar()호출을 줄이는게 편해서 배열로 바꿔주었는데, 
해당 문제의 경우 문자열을 한 번만 순회하므로 성능 차이가 크지 않기에 charAt() 사용이 코드 가독성 측면에서도 좋고,
메모리 사용량 측면에서도 charAt()이 유리하다고 생각했습니다.
시간 복잡도는 두 경우 모두 한번만 순회하기 때문에 O(N)이지만, 첫 코드는 재귀 호출 구조로 인해 추가 메모리가 소비될 것 같아 두번째 코드가 더 좋은 코드 같다고 생각합니다.
개선할 점 있다면 의견 주시면 감사하겠습니다!
=> [Programmers] 문자열 나누기 - 김태현

Programmers/jiwoong/수레 움직이기.java
- 이전에 풀어봤던 문제라 빨리 풀었습니다..! 
- 피드백 자유롭게 하셔도 됩니다!
=> [Programmers] 수레 움직이기 - 허지웅

Baekjoon/taehyoun/집합.java
처음에 HashSet으로 접근이후 비트마스크 풀이로도 접근 해봤습니다. 
제 코드로는 메모리나 시간 둘다 큰 차이가 없는거 같은데 이유 아시는분 계실까요?
제 생각에는 집합 원소가 비교적 적은 20개로 한정되서 그런것 같은데, 메모리, 시간 둘다 비슷한건 의문이네요.
=> [Baekjoon] 집합 - 김태현

Baekjoon/seungheon/집합.java
처음에는 평소대로 문제를 풀고 제출했습니다.
하지만 풀고나서 제 코드를 다시 보니 결국 집합 내부에 해당 값이 "존재한다 vs. 하지 않는다" 로 논리가 나뉘더라구요.
그래서 이에 맞게 비트 연산을 활용하여 코드를 개선했습니다!
=> [Baekjoon] 집합 - 백승헌

Baekjoon/byeongun/집합.java
=> [Silver V] 집합 - 양병운

Baekjoon/jiwoong/집합.java
- HashSet 으로 안풀려서 bitmasking 공부좀 했습니다!
- https://loosie.tistory.com/238
- 참조하시면 좋을 것 같습니다
=> [Silver V] 집합 - 허지웅

Programmers/seungheon/석유시추.java, Programmers/seungheon/충돌위험 찾기.java
chunkId 를 이미 체크했는지의 여부를 검사하기 위해 set 을 사용했습니다.
해시테이블 혹은 트리구조와 같이 검색이 순차적인 자료구조에 비해 빠르기에 선택했는데, 혹시 이 말고 다른 방법이 있으시다면 공유 부탁드려요!
=> [Programmers] 석유 시추 - 백승헌

Programmers/jiwoong/석유시추.java
- 풀이 1 은 그래프 탐색을 사용했습니다
- 풀이 2 는 UnionFind 를 사용했습니다
=> [Programmers] 석유시추 - 허지웅

Programmers/byeongun/석유 시추.java
프로그래머스에서 돌리면 실행 결과는 모두 통과했지만 효율성 측면에서 탈락했습니다. 
좀 더 이해하고 수정하려면 시간이 걸릴 것 같아서 커밋 메시지 보내 놓고 남는 시간 다른 분들 코드 보면서 효율성 측면에서 어떻게 코딩하셨는지 생각하는 시간 가지겠습니다!
=> [Programmers] 석유 시추 - 양병운 

Programmers/byeongun/충돌위험 찾기.java
테스트는 성공했습니다.
그런데 여기서도 효율성 때문에 시간초과가 나오는 것 같습니다..
효율성 측면에서 좀 더 노력해보겠습니다!
=> [Programmers] 충돌 위험 찾기 - 양병운

LeetCode/jiwoong/KthSmallestElementInABST.java
=> [LeetCode] Kth Smallest Element In A BST - 허지웅

LeetCode/taehyoun/Kth Smallest Element in a BST.java
재귀로 풀이한 뒤에 스택 풀이와 비교해보면서 학습해봤습니다!
=> [LeetCode] Kth Smallest Element in a BST - 김태현

Baekjoon/seungheon/기타 레슨.java
`bw.write(Integer.toString(start));` 때문에 헤맸습니다.. 분명 로직은 다 맞는데 왜 20% 대에서 안 풀리지 했더니 `bw.write(start)` 로 적었더군요
=> [Baekjoon] 기타 레슨 - 백승헌

Baekjoon/ssen/기타_레슨.java, LeetCode/ssen/Number of 1 Bits.java
github에 새로운 방식에 적응하느라 ㅠㅠ 시간이 좀 걸렸습니다...
혹시나 PR 방식에 문제점이 있다면 코멘트 부탁드립니다!
=> [Silver I] 기타 레슨 - 조세은/ [Easy] Number of 1 Bits

Baekjoon/byeongun/기타 레슨.java
[Baekjoon] 기타 레슨 - 양병운 
IDE에서 직접 수정해도 답은 잘 나오는데 백준에서 계속 런타임 오류로 런타임 에러 (NumberFormat)가 뜨네요.. gpt로 잡으려고 했지만 계속 실패해서 일단 한 곳까지 올립니다.
정답지를 보고도 한~참을 보고 어떻게 푸는 건지 이해했네요.. 
임의의 중간 수를 바탕으로 나눴을 때 몇 개로 나눠지는 지 M개에 따라 블루레이의 크기를 늘릴지 줄일지 결정하여 답을 얻어내는 구조군요..
뭔가 저는 너무 직관적으로 다가가는 느낌이네요 ㅠㅜ
=> [Baekjoon] 기타 레슨 - 양병운

Baekjoon/jiwoong/기타 레슨.java
=> [Baekjoon] 기타 레슨 -허지웅

LeetCode/byeongun/Number of 1 Bits.java
[LeetCode] Number of 1 Bits - 양병운
=> [LeetCode] Number of 1 Bits - 양병운 

Programmers/ssen/뒤에 있는 큰 수 찾기.java
배열 문제를 개미수열을 풀어 보았던게 도움이 되었습니다!
=> [Programmers] 뒤에 있는 큰 수 찾기 - 조세은

Programmers/seungheon/뒤에 있는 큰 수 찾기.java
=> [Programmers] 뒤에 있는 큰 수 찾기 - 백승헌

Programmers/byeongun/뒤에 있는 큰 수 찾기.java
[Programmers] 뒤에 있는 큰 수 찾기 - 양병운
=> [Programmers] 뒤에 있는 큰 수 찾기 - 양병운 

Programmers/taehyoun/달리기 경주.java, Programmers/taehyoun/할인 행사.java
첫시도에 want 리스트에 있는 품목이 아닐 경우 skip 처리하는 로직을 생각하지 못했다.
=> [Programmers] 할인 행사 - 김태현

Programmers/byeongun/수레 움직이기.java
=> [Programmers] 수레 움직이기 - 양병운

Baekjoon/taehyoun/단지번호붙이기.java
배운점 : PriorityQueue는 iterator로 순회 X
=> [Baekjoon] 단지번호붙이기 - 김태현

LeetCode/seungheon/Container With Most Water.java
처음엔 투포인터 시작과 끝을 0번 인덱스부터 설정했는데, 제출 시 틀리는 케이스가 나오더군요
그래서 결국 힌트 보고 끝을 마지막 인덱스로 설정해주고 풀었습니다!
=> [LeetCode] Container With Most Water - 백승헌

LeetCode/taehyoun/Container With Most Water.java
배운점 : height가 작은 쪽을 이동하는 아이디어 (큰쪽은 이동해봤자 더 큰 값을 기대할 수 없음)
=> [LeetCode] Container With Most Water - 김태현

LeetCode/byeongun/ContainerWithMostWater.java
[LeetCode] Container With Most Water - 양병운
=> [LeetCode] Container With Most Water - 양병운

Programmers/byeongun/가운데 글자 가져오기.java
[Programmers] 가운데 글자 가져오기 - 양병운
=> [Programmers] 가운데 글자 가져오기 - 양병운

Baekjoon/byeongun/두 용액.java
=> [Baekjoon] 두 용액 - 양병운

Baekjoon/byeongun/수 찾기.java
=> [Baekjoon] 수 찾기 - 양병운 

Programmers/jiwoong/과일장수.java
=> [Programmers] 과일 장수 - 허지웅

Programmers/seungheon/숫자 변환하기.java
오전에 풀었는데, PR 올린 줄 알았네요 ㅜㅜ 죄송합니다
처음엔 그리디로 접근했는데 정답률이 50이더군요..
그래서 dp로 풀이했습니다!
=> [Programmers] 숫자 변환하기 - 백승헌

Programmers/byeongun/숫자 변환하기.java
처음 DFS로 생각해서 풀다가 시간 초과를 해결할 수 없어 BFS로 다시 풀어 해결했습니다..
최소 거리 구할 때는 BFS로 풀어야 한다는 교훈을 얻었네요.
=> [Programmers] 숫자 변환하기 - 양병운 

Programmers/jiwoong/붕대감기.java
=> [Programmers] 붕대 감기 - 허지웅

Programmers/taehyoun/붕대 감기.java
풀이 후 여러 코드를 보았는데 대부분 시간을 +1씩 증가하면서 계산하는 방식으로 풀이한거 같다.
내 풀이 : 공격 당하지 않은 구간을 계산하여 구간 단위로 체력을 개산하는 방식으로 공격 당하지 않은 구간이 긴 케이스에 유리하다 생각한다.
=> [Programmers] 붕대 감기 - 김태현

Programmers/seungheon/붕대 감기.java
=>  [Programmers] 붕대 감기 - 백승헌 

Programmers/ssen/붕대 감기.java
=> [Programmers] 붕대 감기 - 조세은

Programmers/붕대 감기.java
=> [Programmers] 붕대 감기 - 양병운

Programmers/taehyoun/퍼즐 게임 챌린지.java
=> [Programmers]  퍼즐 게임 챌린지 - 김태현

Programmers/jiwoong/퍼즐 게임 챌린지.java
=> [Programmers] 퍼즐 게임 챌린지 - 허지웅

Baekjoon/taehyoun/두 용액.java
=> [Baekjoon] 두 용액 - 김태현

Programmers/byeongun/퍼즐 게임 챌린지.java
로직까지 잘 구현 했다가 
level을 1-2-3-4 씩 증가시키다가 반전되면 다시 (-1)-(-2).. 가는 것으로 생각했는데 
알고보니까 이분 탐색을 사용하는 게 핵심이었나보네요.
결과값도 처음에 int 로 잡았다가 마지막 테스트에서 계속 마이너스가 떠서 왜 그렇지 30분 고민했다가 설마 하면서 long타입으로 바꿨더니 성공했습니다 ㅠㅜ
=> [Programmers] 퍼즐 게임 챌린지 - 양병운

Programmers/seungheon/퍼즐 게임 챌린지.java
=> [Programmers] 퍼즐 게임 챌린지 - 백승헌

Programmers/ssen/퍼즐 게임 챌린지.java
=> [Programmers] 퍼즐 게임 챌린지 - 조세은

Baekjoon/jiwoong/N과M.java
=> [Baekjoon] N과 M - 허지웅

Baekjoon/jiwoong/호텔대실.java
=> [Programmers] 호텔 대실 - 허지웅

Baekjoon/jiwoong/공원산책.java
=> [Programmers] 공원 산책 - 허지웅

LeetCode/seungheon/Invert Binary Tree.java
=> [LeetCode] Invert Binary Tree - 백승헌

Programmers/jiwoong/추억 점수.java
=> [Programmers] 추억 점수 - 허지웅

Programmers/seungheon/추억 점수.java
=> [Programmers] 추억 점수 - 백승헌

Programmers/taehyoun/추억 점수.java
=> [Programmers] 추억 점수 - 김태현

Programmers/byeongun/추억 점수.java
[Programmers] 추억 점수 - 양병운
[Lv. 1] 추억 점수
=> [Programmers] 추억 점수 - 양병운

Programmers/taehyoun/크레인 인형뽑기 게임.java
첫시도 오답 : map.put(i+1, map.getOrDefault(i+1, new ArrayDeque<>()).offer(board[i][j]));
map.getOrDefault로 아이템리스트 가져온뒤 board[i][j] 넣어주는 것을 의도했는데 offer는 boolean 타입을 리턴하기 때문에 결과적으로 
map.put(i+1, boolean 타입)을 시도한것으로 오류발생
위의 로직을 단계적으로 올바르게 바꾸어 준다면 다음과 같다.
Deque<Integer> deque = map.getOrDefault(i+1, new ArrayDeque<>());
deque.offer(board[i][j]);
map.put(i+1, deque); 
computeIfAbsent를 사용하면 다음과 같이 한줄로 표현이 가능하다. (computeIfAbsent는 Deque을 반환)
map.computeIfAbsent(i+1, k -> new ArrayDeque<>()).offer(board[i][j]);
=> [Programmers] 크레인 인형뽑기 게임 - 김태현

Programmers/jiwoong/크레인 인형뽑기 게임.java
=> [Programmers] 크레인 인형뽑기 게임 - 허지웅

Programmers/byeongun/크레인 인형뽑기 게임.java
[Lv. 1] 크레인 인형뽑기 게임
board[][]를 Stack으로 잘 뽑아서 뽑기 리스트 배치는 잘 했는데
move를 for문으로 돌릴 생각을 못했네요. 또한 Visited에 들어있는지 없는지 확인하기 위해서 for문 돌기 전에 미리 add했는데 이게 비어있는 공간을 add 할 수 있는 걸 생각 못했네요.
=> [Programmers] 크레인 인형뽑기 게임 - 양병운 

Programmers/seungheon/크레인 인형뽑기 게임.java
=> [Programmers] 크레인 인형뽑기 게임 - 백승헌

Programmers/seungheon/택배상자.java
=> [Programmers] 택배상자 - 백승헌

Programmers/jiwoong/택배상자.java
=> [Programmers] 택배상자 - 허지웅

Programmers/byeongun/택배상자.java
=> [Programmers] 택배상자 - 양병운 

Programmers/seungheon/두 큐 합 같게 만들기.java
=> [Programmers] 두 큐 합 같게 만들기 - 백승헌

Programmers/byeongun/두 큐 합 같게 만들기.java
[Programmers] 두 큐 합 같게 만들기 - 양병운
=> [Programmers] 두 큐 합 같게 만들기 - 양병운

Programmers/jiwoong/두 큐 합 같게 만들기.java
=> [Programmers] 두 큐 합 같게 만들기 - 허지웅

Programmers/taehyoun/두 큐 합 같게 만들기.java
=> [Programmers] 두 큐 합 같게 만들기 - 김태현

LeetCode/seungheon/Symmetric Tree.java
=> [LeetCode] Symmetric Tree - 백승헌

LeetCode/jiwoong/Symmetric Tree.java
=> [LeetCode] Symmetric Tree - 허지웅

LeetCode/taehyoun/Symmetric Tree.java
저번에 푼 문제랑 비슷한 문제 같아서 풀 수 있을 줄 알았는데 혼자 힘으로는 못 풀었네요.. 비슷한 문제들을 좀 더 풀어보고 공부해보려 합니다
=> [LeetCode] Symmetric Tree - 김태현

Programmers/byeongun/요격 시스템.java
테스트 통과와 직접 테스트 작성 했을 때 통과하는데 실제 채점 값은 메모리, 시간 초과가 일어나네요 ㅠㅜ
정답 코드 보면서 좀 더 공부해 보겠습니다 ㅠㅜ
=> [Programmers] 요격 시스템 - 양병운

Programmers/jiwoong/요격 시스템.java
=> [Programmers] 요격 시스템 - 허지웅

Programmers/seungheon/요격 시스템.java
=> [Programmers] 요격 시스템 - 백승헌

Programmers/taehyoun/요격 시스템.java
=> [Programmers] 요격 시스템 - 김태현

Baekjoon/taehyoun/DFS와 BFS.java
=> [Baekjoon] DFS와 BFS - 김태현

Baekjoon/seungheon/DFS 와 BFS.java
=> [Baekjoon] DFS 와 BFS - 백승헌

Programmers/taehyoun/구명보트.java
풀리긴 했는데 왜 맞는 풀이인지 확신이 안되서 다른 풀이를 찾아보려고 합니다.
만약 보트에 인원 제한이 없을 경우는 어떻게 접근해야 될까요? 배낭 채우기 문제로 바뀌는거 같긴한데, 왜 2명(혹은 인원 제한이 있을 경우)으로 제한이 생기면 문제 접근이 아예 달라질까 아직 더 생각해봐야겠네요
=> [Programmers] 구명보트 - 김태현

Programmers/seungheon/구명보트.java
=> [Programmers] 구명보트 - 백승헌

Baekjoon/byeongun/DFS 와 BFS.java
=> [Baekjoon] DFS와 BFS - 양병운

Programmers/byeongun/구명보트.java
=> [Programmers] 구명보트 - 양병운

Programmers/jiwoong/구명보트.java
=> [Programmers] 구명보트 - 허지웅

Baekjoon/byeongun/숫자 정사각형.java
=> [Baekjoon] 숫자 정사각형 - 양병운 

Baekjoon/taehyoun/숫자 정사각형.java
=> [Baekjoon] 숫자 정사각형 - 김태현

Baekjoon/jiwoong/숫자 정사각형.java
=> [Baekjoon] 숫자 정사각형 - 허지웅

LeetCode/taehyoun/Path Sum.java
제 첫 오답 코드가 틀린 이유를 아직 잘 모르겠습니다. 의견 부탁드립니다!!
=> [LeetCode] Path Sum - 김태현

LeetCode/byeongun/Path Sum.java
=> [LeetCode] Path Sum - 양병운

LeetCode/seungheon/Path Sum.java
=> [LeetCode] Path Sum - 백승헌

LeetCode/taehyoun/Count Complete Tree Nodes.java
=> [LeetCode] Count Complete Tree Nodes - 김태현

Programmers/taehyoun/공원.java
=> [Programmers] 공원 - 김태현

LeetCode/jiwoong/Count Complete Tree Nodes.java
=> [LeetCode] Count Complete Tree Nodes - 허지웅

LeetCode/seungheon/Count Complete Tree Nodes.java
처음에 많이 헤맸습니다 ㅠ
그래서 discussion 을 참고했고, 이 기회에 완전이진트리의 성질을 배열이 아닌 노드로 이해하게 됐습니다!
=> [LeetCode] Count Complete Tree Nodes - 백승헌

LeetCode/Count Complete Tree Nodes.java, Programmers/byeongun/공원.java
[LeetCode] Count Complete Tree Nodes - 양병운
=> [LeetCode] Count Complete Tree Nodes - 양병운

Programmers/jiwoong/공원.java
=> [Programmers] 공원 - 허지웅

Baekjoon/jiwoong/특정 거리의 도시 찾기.java
=> [Baekjoon] 특정 거리의 도시 찾기 - 허지웅

LeetCode/jiwoong/Average of Levels in Binary Tree.java
=> [LeetCode] Average of Levels in Binary Tree - 허지웅

Programmers/jiwoong/귤 고르기.java
=> [Programmers] 귤 고르기 - 허지웅

LeetCode/taehyoun/Spiral Matrix.java
=> [LeetCode] Spiral Matrix - 김태현

Programmers/jiwoong/서버 증설 횟수.java
=> [Programmers] 서버 증설 횟수 - 허지웅

Programmers/seungheon/공원.java
=> [Programmers] 공원 - 백승헌

Baekjoon/taehyoun/동전 0.java
=> [Baekjoon] 동전 0 - 김태현

Baekjoon/seungheon/동전 0.java
=> [Baekjoon] 동전 0 - 백승헌

Baekjoon/byeongun/동전 0.java
=> [Baekjoon] 동전 0 - 양병운

Baekjoon/jiwoong/동전 0.java
=> [Baekjoon] 동전 0 - 허지웅

Programmers/seungheon/지폐 접기.java
=>  [Programmers] 지폐 접기 - 백승헌

Programmers/jiwoong/지폐 접기.java
=> [Programmers] 지폐 접기 - 허지웅

Baekjoon/byeongun/균형잡힌 세상.java, Programmers/byeongun/지폐 접기.java
=> [Programmers] 지폐 접기 - 양병운

Programmers/taehyoun/지폐 접기.java
=> [Programmers] 지폐 접기 - 김태현

Programmers/taehyoun/귤 고르기.java
=> [Programmers] 귤 고르기 - 김태현

Baekjoon/taehyoun/특정 거리의 도시 찾기.java
=> [Baekjoon] 특정 거리의 도시 찾기 - 김태현

Baekjoon/seungheon/균형잡힌 세상.java
=> [Baekjoon] 균형잡힌 세상 - 백승헌

Baekjoon/taehyoun/균형잡힌 세상.java
=> [Baekjoon] 균형잡힌 세상 - 김태현

Baekjoon/jiwoong/균형잡힌 세상.java
=> [Baekjoon] 균형잡힌 세상 - 허지웅 

LeetCode/taehyoun/Minimum Absolute Difference in BST.java
=> [LeetCode] Minimum Absolute Difference in BST - 김태현

LeetCode/byeongun/Convert Sorted Array to Binary Search Tree.java
[LeetCode] Convert Sorted Array to Binary Search Tree - 양병운
=> [LeetCode] Convert Sorted Array to Binary Search Tree - 양병운

LeetCode/seungheon/Convert Sorted Array to Binary Search Tree.java
=> [LeetCode] Convert Sorted Array to Binary Search Tree - 백승헌

LeetCode/jiwoong/Convert Sorted Array to Binary Search Tree.java
=> [LeetCode] Convert Sorted Array to Binary Search Tree - 허지웅

LeetCode/taehyoun/Convert Sorted Array to Binary Search Tree.java
=> [LeetCode] Convert Sorted Array to Binary Search Tree - 김태현

Programmers/jiwoong/기사단원의 무기.java
=> [Programmers] 기사단원의 무기 - 허지웅

Baekjoon/jiwoong/나무 자르기.java
=> [Baekjoon] 나무 자르기 - 허지웅

Programmers/jiwoong/미로 탈출.java
=> [Programmers] 미로 탈출 - 허지웅

Programmers/jiwoong/행렬 테두리 회전하기.java
=> [Programmers] 행렬 테두리 회전하기 - 허지웅

LeetCode/jiwoong/Climbing Stairs.java
=> [LeetCode] Climbing Stairs - 허지웅

Programmers/byeongun/기사단원의 무기.java
[Programmers] 기사단원의 무기 - 양병운 
테스트랑 체점 모두 통과했는데 좀 더 효율적인 코드를 보고 싶어서 확인했는데 
1부터 10까지 2 의 약수를 가지는 수가 10/2 = 5개 라는 게 생각지도 못한 방법으로 풀어서 놀랐습니다
물론 2x1, 2x2, 2x3 식으로 생각하면 당연하다고 생각할 수 있는데 약수의 수가 N/i로 될 수 있다는 거를 꺠달았네요.
=> [Programmers] 기사단원의 무기 - 양병운 

Programmers/taehyoun/기사단원의 무기.java
=> [Programmers] 기사단원의 무기 - 김태현

LeetCode/taehyoun/Climbing Stairs.java
=> [LeetCode] Climbing Stairs - 김태현

Baekjoon/taehyoun/나무 자르기.java
오답 이유: low를 가장 작은 나무 높이로 설정하여 가장 작은 나무가 잘리는 경우를 고려하지 않게됨)
0으로 수정 후 통과
=> [Baekjoon] 나무 자르기 - 김태현

Programmers/taehyoun/미로 탈출.java
오답 이유 : queue에서 point를 poll할 때 방문처리를 하였음. queue에 들어가있지만 아직 방문처리가 되지 않은 point들이 중복해서 queue 들어가는 문제 발생 => 메모리 초과
해결 : queue에 point를 넣는 시점에 방문처리함
=> [Programmers] 미로 탈출 - 김태현

Programmers/jiwoong/연속 부분 수열 합의 개수.java
=> [Programmers] 연속 부분 수열 합의 개수 - 허지웅

Programmers/taehyoun/연속 부분 수열 합의 개수.java
=> [Programmers] 연속 부분 수열 합의 개수 - 김태현

Programmers/byeongun/연속 부분 수열 합의 개수.java
[Programmers] 연속 부분 수열 합의 개수 - 양병운
=> [Programmers] 연속 부분 수열 합의 개수 - 양병운

Programmers/byeongun/124 나라의 숫자.java
=> [Programmers] 나라의 숫자 - 양병운

Programmers/seungheon/기사단원의 무기.java
처음에 약수의 개수를 O(n) 이 걸리게 구현해서 시간 초과가 났습니다.
분명 다른 효율적인 공식이 있었는데 기억이 나질 않아 참고해서 풀었습니다.
=> [Programmers] 기사단원의 무기 - 백승헌

Programmers/seungheon/연속 부분 수열 합의 개수.java
=> [Programmers] 연속 부분 수열 합의 개수 - 백승헌

Programmers/seungheon/124 나라의 숫자.java
=> [Programmers] 124 나라의 숫자 - 백승헌

Programmers/jiwoong/124 나라의 숫자.java
=> [Programmers] 124 나라의 숫자 - 허지웅

Baekjoon/byeongun/체스판 다시 칠하기.java
=> [Baekjoon] 체스판 다시 칠하기 - 양병운

Baekjoon/taehyoun/체스판 다시 칠하기.java
=> [Baekjoon] 체스판 다시 칠하기 - 김태현

Baekjoon/jiwoong/체스판 다시 칠하기.java
=> [Baekjoon] 체스판 다시 칠하기 - 허지웅

Baekjoon/seungheon/체스판 다시 칠하기.java
=> [Baekjoon] 체스판 다시 칠하기 - 백승헌

LeetCode/byeongun/Jump Game.java
=> [LeetCode] Jump Game - 양병운

LeetCode/taehyoun/Jump Game.java
=> [LeetCode] Jump Game - 김태현

LeetCode/jiwoong/Jump Game.java
=> [LeetCode] Jump Game - 허지웅

LeetCode/seungheon/Remove Duplicates from Sorted Array II.java
계속 삽질하다 결국 답을 참고했습니다.
아직도 완전히 이해하지 못해서 더 공부해야겠습니다.
=> [LeetCode] Remove Duplicates from Sorted Array II - 백승헌

LeetCode/taehyoun/Remove Duplicates from Sorted Array II.java
=> [LeetCode] Remove Duplicates from Sorted Array II - 김태현

LeetCode/byeongun/Remove Duplicates from Sorted Array II.java
한시간 정도 고민했는데 안돼서 답안을 봤습니다..
저는 바꿔줄 수를 변수로 잡았는데 답안은 정렬해서 올라가는 배열을 변수로 잡더군요..
11122 면 1이 2번 중복되는 차례에 afternum++ 해서 2를 가리킨 후 배열 순회하는 i+1 값에 넣어주면서 정렬해서 올라가려고 했는데 GPT에 물어봐도 잘 안되고 틀린 접근 같습니다..
답안은 배열 순회를 afternum으로 잡고 정렬하면서 올라가는 값을 변수로 잡았는데
다음 비슷한 문제 있으면 정렬하면서 올라갈 때는 배열 순회하는 쪽을 앞쪽 변수로 잡아서 가는 쪽으로 가보겠습니다.
(( 스프린트 미션이랑 진도 복습 떄문에 시간이 없어서 한 시간동안만 고민하고 답안 확인하고 시간 부족으로 제출합니다. ))
=> [LeetCode] Remove Duplicates from Sorted Array II - 양병운

LeetCode/jiwoong/Remove Duplicates from Sorted Array II.java
=> [LeetCode] Remove Duplicates from Sorted Array II - 허지웅

Programmers/taehyoun/푸드 파이트 대회.java
=> [Programmers] 푸드 파이트 대회 - 김태현

Programmers/taehyoun/행렬 테두리 회전하기.java
=> [Programmers] 행렬 테두리 회전하기 - 김태현

Programmers/taehyoun/캐시.java
=> [Programmers] 캐시 - 김태현

Programmers/seungheon/푸드 파이트 대회.java
=> [Programmers] 푸드 파이트 대회 - 백승헌

Programmers/jiwoong/푸드 파이트 대회.java
=> [Programmers] 푸드 파이트 대회 - 허지웅

Baekjoon/taehyoun/상근이의 여행.java
=> [Baekjoon] 상근이의 여행 - 김태현

Baekjoon/jiwoong/상근이의 여행.java
=> [Baekjoon] 상근이의 여행 - 허지웅

Baekjoon/byeongun/상근이의 여행.java
=> [Baekjoon] 상근이의 여행 - 양병운

Programmers/byeongun/대충 만든 자판.java
=> [Programmers] 대충 만든 자판 - 양병운

Baekjoon/seungheon/상근이의 여행.java
풀고 나서 굳이 BFS 로 풀어야 했나 싶어 답안을 확인했는데,
MST 성질을 활용해서 O(1) 로 풀 수 있는 문제이더군요.. 그래프 이론 좀 다시 공부해야겠습니다
=> [Baekjoon] 상근이의 여행 - 백승헌

Programmers/seungheon/대충 만든 자판.java
=> [Programmers] 대충 만든 자판 - 백승헌

Programmers/taehyoun/대충 만든 자판.java
=> [Programmers] 대충 만든 자판 - 김태현

Programmers/jiwoong/대충 만든 자판.java
=> [Programmers] 대충 만든 자판 - 허지웅

Baekjoon/byeongun/2×n 타일링.java
=> [Baekjoon] 2×n 타일링 - 양병운

Baekjoon/jiwoong/2xn 타일링.java
=> [Baekjoon] 2×n 타일링 - 허지웅

Baekjoon/seungheon/2×n 타일링.java
=> [Baekjoon] 2×n 타일링 - 백승헌

LeetCode/jiwoong/Gas Station.java
=> [LeetCode] Gas Station - 허지웅

LeetCode/byeongun/Add Binary.java
Integer.parse( i, 2) 만 알고 있다가 BigInteger 라는 타입은 처음 접했네요..
=> [LeetCode] Add Binary - 양병운

LeetCode/jiwoong/Add Binary.java
=> [LeetCode] Add Binary - 허지웅 

LeetCode/seungheon/Gas Station.java
이것저것 시도해보다가 discussion 을 참고해서 풀이했습니다😅
=> [LeetCode] Gas Station - 백승헌

LeetCode/seungheon/Add Binary.java
=> [LeetCode] Add Binary - 백승헌

Baekjoon/ATM.java, Programmers/byeongun/체육복.java
=> [Programmers] 체육복 - 양병운

Baekjoon/taehyoun/2×n 타일링.java
=> [Baekjoon] 2×n 타일링 - 김태현

Baekjoon/taehyoun/ATM.java
=> [Baekjoon] ATM - 김태현

Programmers/byeongun/하샤드 수.java
=> [Programmers] 하샤드 수 - 양병운

Programmers/jiwoong/체육복.java
=> [Programmers] 체육복 - 허지웅

Programmers/taehyoun/하샤드 수.java
=> [Programmers] 하샤드 수 - 김태현

Programmers/jiwoong/하샤드 수.java
=> [Programmers] 하샤드 수 - 허지웅

Baekjoon/byeongun/빙고.java, Programmers/byeongun/멀리 뛰기.java
=> [Baekjoon] 빙고 - 양병운

LeetCode/byeongun/Search Insert Position.java, Programmers/byeongun/줄 서는 방법.java
[LeetCode]  Search Insert Position - 양병운
=> [LeetCode]  Search Insert Position - 양병운 

Programmers/seungheon/체육복.java
=> [Programmers] 체육복 - 백승헌

Programmers/jiwoong/멀리 뛰기.java
=> [Programmers] 멀리 뛰기 - 허지웅

Baekjoon/taehyoun/빙고.java
=> [Baekjoon] 빙고 - 김태현

Baekjoon/taehyoun/덱.java
=> [Baekjoon] 덱 - 김태현

Programmers/seungheon/예상 대진표.java
=> [Programmers] 예상 대진표 - 백승헌

Programmers/예상 대진표.java
=> [Programmers] 예상 대진표 - 양병운

Baekjoon/jiwoong/덱.java
=> [Baekjoon] 덱 - 허지웅

Programmers/taehyoun/예상 대진표.java
생각 & 배운점
n을 준 이유는 잘 모르겠지만 사용 안했음
배운점 : 숏코드를 보고 나서 홀,짝을 구분할 필요없이 +1 한뒤 나누기 2 하는 것으로 동일하게 처리가능함을 꺠닳음
=> [Programmers] 예상 대진표 - 김태현

LeetCode/taehyoun/Single Number.java
=> [LeetCode] Single Number - 김태현

LeetCode/jiwoong/Single Number.java
=> [LeetCode] Single Number - 허지웅

LeetCode/byeongun/Single Number.java, LeetCode/byeongun/plus-one.java
[LeetCode] Single Number - 양병운
=> [LeetCode] Single Number - 양병운

LeetCode/seungheon/Single Number.java
=> [LeetCode] Single Number - 백승헌

LeetCode/taehyoun/Plus One.java
=> [LeetCode] Plus One - 김태현

LeetCode/jiwoong/Plus One.java
=> [LeetCode] Plus One - 허지웅

Programmers/byeongun/H-Index.java
=> [Programmers] H-Index - 양병운

Programmers/taehyoun/H-Index.java
=> [Programmers] H-Index - 김태현

Programmers/jiwoong/H-Index.java
=> [Programmers] H-Index - 허지웅

Baekjoon/jiwoong/바닥 장식.java
=> [Silver IV] 바닥 장식

Baekjoon/taehyoun/바닥 장식.java
=> [Baekjoon]  바닥 장식 - 김태현

LeetCode/seungheon/Plus One.java
=> [LeetCode] Plus One - 백승헌

Baekjoon/seungheon/바닥 장식.java
=> [Baekjoon] 바닥 장식 - 백승헌

Baekjoon/byeongun/바닥 장식.java
=> [Baekjoon] 바닥 장식 - 양병운

Programmers/jiwoong/피로도.java
=> [Programmers] 피로도 - 허지웅

Programmers/byeongun/피로도.java
=> [Programmers] 피로도 - 양병운

Programmers/seungheon/피로도.java
=> [Programmers] 피로도 - 백승헌

Baekjoon/seungheon/예산.java
=> [Baekjoon] 예산 - 백승헌

Baekjoon/byeongun/예산.java
=> [Baekjoon] 예산 - 양병운

Programmers/seungheon/2개 이하로 다른 비트.java
=> [Programmers] 2개 이하로 다른 비트 - 백승헌

Programmers/taehyoun/정수 삼각형.java, Programmers/taehyoun/피로도.java
필요 피로도, 소모 피로도 등의 정렬 기준을 세워 그리디로 접근했다가, backtracking으로 해결했습니다.
특정 던전을 탐험한 후의 피로도가 다음 선택에 영향을 미치는 경우처럼 의존성이 있는 문제는 그리디로 해결하기 어렵다는 것을 알게되었고,
해당 문제의 경우 던전의 개수가 최대 8개로 제한되어 있어 8! = 40320개 이하로 완전탐색으로 접근해도 충분했다는 점도 알게되었습니다.
=> [Programmers] 피로도 - 김태현

Baekjoon/taehyoun/예산.java
=> [Baekjoon] 예산 - 김태현

Baekjoon/jiwoong/예산.java
=> [Baekjoon] 예산 - 허지웅

Programmers/byeongun/2개 이하로 다른 비트.java, Programmers/byeongun/정수 삼각형.java
[Programmers] 2개 이하로 다른 비트 - 양병운
=> [Programmers] 2개 이하로 다른 비트 - 양병운

Programmers/seungheon/정수 삼각형.java
=> [Programmers] 정수 삼각형 - 백승헌

Programmers/jiwoong/정수 삼각형.java
=> [Programmers] 정수 삼각형 - 허지웅

Programmers/byeongun/튜플.java
=> [Programmers] 튜플 - 양병운

Programmers/seungheon/튜플.java
=> [Programmers] 튜플 - 백승헌

Programmers/seungheon/두 개 뽑아서 더하기.java
=> [Programmers] 두 개 뽑아서 더하기 - 백승헌

Baekjoon/seungheon/친구.java
=> [Baekjoon] 친구 - 백승헌

Programmers/seungheon/모의고사.java, Programmers/seungheon/행렬의 곱셈.java
=> [Programmers] 모의고사, 행렬의 곱셈 - 백승헌

Baekjoon/byeongun/친구.java
=> [Baekjoon] 친구 - 양병운

Programmers/byeongun/실패율.java
레벨 1인데 생각보다 어려워서 놀랐습니다 
challengers 배열도 처음에는 Map<Integer, Double> 로만 풀려다가 안풀렸네요...
배열(int[]) 순서를 활용해서 배열 안에 값을 넣으면 자동으로 Map<Int, Double> 처럼 보이도록 하는 것을 생각 못했네요 
그리고 sorted하면서 배열 정리하는 것도 다시 상기한 것 같습니다.
=> [Programmers] 실패율 - 양병운

Programmers/byeongun/방문 길이.java
=> [Programmers] 방문 길이 - 양병운

Programmers/seungheon/실패율.java
=> [Programmers] 실패율- 백승헌

Programmers/seungheon/방문 길이.java
=> [Programmers] 방문 길이 - 백승헌

Programmers/byeongun/올바른 괄호.java
=> [Programmers] 올바른 괄호 - 양병운

Programmers/seungheon/올바른 괄호.java
=> [Programmers] 올바른 괄호 - 백승헌

Programmers/taehyoun/올바른 괄호.java
=> [Programmers] 올바른 괄호 - 김태현

Programmers/byeongun/괄호 회전하기.java
=> [Programmers] 괄호 회전하기 - 양병운

Programmers/seungheon/괄호 회전하기.java
=> [Programmers] 괄호 회전하기 - 백승헌

Programmers/taehyoun/괄호 회전하기.java
=> [Programmers] 괄호 회전하기 - 김태현

Programmers/byeongun/주식가격.java
[Programmers] 주식가격 - 양병운
이중 배열로 푸는 문제는 아닐 것 같아서 다르게 풀어보려고 했다가 stack이라는 힌트는 얻긴 했는데
value 값에만 집중했다가 답안을 보고 인덱스를 stack으로 활용하는 방법을 깨달았네요.
로직을 이해하는데 20분 걸린 것 같습니다 ㅠㅜ
참고 링크 : https://girawhale.tistory.com/7
=> [Programmers] 주식가격 - 양병운

Programmers/jiwoong/두 개 뽑아서 더하기.java
=> [Programmers] 두 개 뽑아서 더하기 - 허지웅

Baekjoon/jiwoong/전쟁 - 전투.java
=> [Baekjoon] 전쟁 - 전투 - 허지웅

Programmers/jiwoong/혼자서 하는 틱택토.java
=> [Programmers] 혼자서 하는 틱택토 - 허지웅

Programmers/taehyoun/짝지어 제거하기.java
=> [Programmers] 짝지어 제거하기 - 김태현

Programmers/taehyoun/주식가격.java
병운님이 첨부해주신 링크 참고하여 스택 활용한 풀이 공부 후 제출합니다!
=> [Programmers] 주식가격 - 김태현

Baekjoon/byeongun/요세푸스 문제.java
=> [Baekjoon] 요세푸스 문제 - 양병운

Programmers/byeongun/기능개발.java, Programmers/byeongun/카드 뭉치.java
=> [Programmers] 카드 뭉치 - 양병운

Baekjoon/taehyoun/요세푸스 문제.java
=> [Baekjoon] 요세푸스 문제 - 김태현

Programmers/taehyoun/카드 뭉치.java
=> [Programmers] 카드 뭉치 - 김태현

Programmers/byeongun/완주하지 못한 선수.java, Programmers/byeongun/할인 행사.java
[Programmers] 할인 행사 - 양병운
- [x ] PR 제목이 '[플랫폼명] 문제 제목 - 작성자' 형식을 따르고 있나요?
=> [Programmers] 할인 행사 - 양병운

Programmers/jiwoong/모음사전.java
=> [Programmers] 모음사전 - 허지웅

Programmers/byeongun/오픈채팅방.java
=> [Programmers] 오픈채팅방 - 양병운

Programmers/byeongun/베스트앨범.java
=> [Programmers] 베스트앨범 - 양병운

Programmers/byeongun/메뉴 리뉴얼.java, Programmers/byeongun/신고 결과 받기.java
=> [Programmers] 신고 결과 받기 - 양병운

Programmers/taehyoun/기능개발.java
=> [Programmers] 기능개발 - 김태현

Programmers/seungheon/짝지어 제거하기.java
=> [Programmers] 짝지어 제거하기 - 백승헌
